// Challenge catalog definition for AI generation
module.exports = {
  TOPICS: [
    // Category 1: LINUX
    { cat: 'LINUX', diff: 'EASY', pts: 100, time: 15, slug: 'linux/easy-cron-env', topic: 'Cron environment variable token extraction' },
    { cat: 'LINUX', diff: 'EASY', pts: 100, time: 15, slug: 'linux/easy-log-grep', topic: 'Hidden file permissions and grep filtering in /var/log' },
    { cat: 'LINUX', diff: 'EASY', pts: 100, time: 10, slug: 'linux/easy-bash-history', topic: 'Base64 encoded string in bash history' },
    { cat: 'LINUX', diff: 'MEDIUM', pts: 200, time: 30, slug: 'linux/med-suid-find', topic: 'SUID find exec command injection' },
    { cat: 'LINUX', diff: 'MEDIUM', pts: 250, time: 35, slug: 'linux/med-tar-wildcard', topic: 'Wildcard tar privilege escalation exploit' },
    { cat: 'LINUX', diff: 'MEDIUM', pts: 250, time: 30, slug: 'linux/med-sudo-hijack', topic: 'Insecure sudo permissions on python script with library hijacking' },
    { cat: 'LINUX', diff: 'HARD', pts: 400, time: 60, slug: 'linux/hard-preload', topic: 'Custom shared library LD_PRELOAD injection in daemon' },
    { cat: 'LINUX', diff: 'HARD', pts: 450, time: 60, slug: 'linux/hard-capabilities', topic: 'Linux capabilities cap_setuid exploitation' },
    { cat: 'LINUX', diff: 'HARD', pts: 450, time: 75, slug: 'linux/hard-nfs-squash', topic: 'Insecure NFS root squashing misconfiguration' },
    { cat: 'LINUX', diff: 'INSANE', pts: 750, time: 120, slug: 'linux/insane-kernel-ioctl', topic: 'Kernel module IOCTL character device vulnerability' },
    { cat: 'LINUX', diff: 'INSANE', pts: 850, time: 150, slug: 'linux/insane-cgroup-escape', topic: 'Namespace breakout via cgroups release_agent' },
    { cat: 'LINUX', diff: 'INSANE', pts: 900, time: 180, slug: 'linux/insane-pam-bypass', topic: 'Custom PAM module authentication bypass exploit' },

    // Category 2: NETWORKING
    { cat: 'NETWORKING', diff: 'EASY', pts: 100, time: 15, slug: 'net/easy-dns-exfil', topic: 'DNS query exfiltration artifact analysis' },
    { cat: 'NETWORKING', diff: 'EASY', pts: 100, time: 15, slug: 'net/easy-http-auth', topic: 'HTTP basic authentication header interception' },
    { cat: 'NETWORKING', diff: 'EASY', pts: 100, time: 15, slug: 'net/easy-icmp-carve', topic: 'ICMP echo request data carving' },
    { cat: 'NETWORKING', diff: 'MEDIUM', pts: 200, time: 30, slug: 'net/med-tls-sni', topic: 'TLS SNI anomaly and covert TCP flag signaling' },
    { cat: 'NETWORKING', diff: 'MEDIUM', pts: 250, time: 40, slug: 'net/med-scada-modbus', topic: 'Modbus industrial SCADA traffic manipulation' },
    { cat: 'NETWORKING', diff: 'MEDIUM', pts: 250, time: 35, slug: 'net/med-asreq-pcap', topic: 'Kerberos pre-authentication AS-REQ hash extraction from PCAP' },
    { cat: 'NETWORKING', diff: 'HARD', pts: 400, time: 60, slug: 'net/hard-bgp-hijack', topic: 'BGP route hijacking and forged routing advertisements' },
    { cat: 'NETWORKING', diff: 'HARD', pts: 450, time: 70, slug: 'net/hard-quic-stream', topic: 'QUIC protocol stream multiplexing covert channel' },
    { cat: 'NETWORKING', diff: 'HARD', pts: 450, time: 75, slug: 'net/hard-custom-proto', topic: 'Custom proprietary binary network protocol reverse engineering' },
    { cat: 'NETWORKING', diff: 'INSANE', pts: 750, time: 120, slug: 'net/insane-doh-channel', topic: 'DNS over HTTPS covert C2 channel traffic analysis with statistical fingerprinting' },
    { cat: 'NETWORKING', diff: 'INSANE', pts: 850, time: 150, slug: 'net/insane-tcp-stego', topic: 'Zero-window TCP sequence number steganography covert data reconstruction' },
    { cat: 'NETWORKING', diff: 'INSANE', pts: 900, time: 180, slug: 'net/insane-wpa3-sae', topic: 'WPA3 SAE Dragonfly handshake offline timing attack artifact' },

    // Category 3: WEB
    { cat: 'WEB', diff: 'EASY', pts: 100, time: 15, slug: 'web/easy-idor-export', topic: 'Insecure direct object reference (IDOR) on profile export endpoint' },
    { cat: 'WEB', diff: 'EASY', pts: 100, time: 15, slug: 'web/easy-xss-search', topic: 'Reflected cross-site scripting (XSS) in search query parameter' },
    { cat: 'WEB', diff: 'EASY', pts: 100, time: 15, slug: 'web/easy-sqli-login', topic: 'SQL injection authentication bypass in login form' },
    { cat: 'WEB', diff: 'MEDIUM', pts: 200, time: 30, slug: 'web/med-jwt-confusion', topic: 'JWT algorithm confusion (HS256 vs RS256) public key signature spoofing' },
    { cat: 'WEB', diff: 'MEDIUM', pts: 250, time: 35, slug: 'web/med-ssrf-metadata', topic: 'Server-side request forgery (SSRF) to cloud instance metadata endpoint' },
    { cat: 'WEB', diff: 'MEDIUM', pts: 250, time: 35, slug: 'web/med-lfi-traversal', topic: 'Path traversal and local file inclusion (LFI) via unvalidated template parameter' },
    { cat: 'WEB', diff: 'HARD', pts: 400, time: 60, slug: 'web/hard-pickle-deser', topic: 'Python pickle insecure deserialization RCE via session cookie' },
    { cat: 'WEB', diff: 'HARD', pts: 450, time: 70, slug: 'web/hard-proto-pollution', topic: 'Prototype pollution leading to remote code execution in Node.js backend' },
    { cat: 'WEB', diff: 'HARD', pts: 450, time: 75, slug: 'web/hard-jinja-ssti', topic: 'Server-side template injection (SSTI) in Jinja2 with sandbox bypass' },
    { cat: 'WEB', diff: 'INSANE', pts: 750, time: 120, slug: 'web/insane-blind-sqli', topic: 'Blind boolean-based SQL injection with time delay and character-by-character extraction over WebSocket' },
    { cat: 'WEB', diff: 'INSANE', pts: 850, time: 150, slug: 'web/insane-phar-pop', topic: 'PHP Phar deserialization exploit chain with custom POP gadgets' },
    { cat: 'WEB', diff: 'INSANE', pts: 900, time: 180, slug: 'web/insane-h2-smuggle', topic: 'HTTP/2 request smuggling desync attack bypassing WAF authentication filter' },

    // Category 4: CRYPTOGRAPHY
  { cat: 'CRYPTOGRAPHY', diff: 'EASY', pts: 100, time: 15, slug: 'crypto/easy-vigenere-caesar', topic: 'Multi-stage Caesar shift and Vigenere cipher decoding' },
  { cat: 'CRYPTOGRAPHY', diff: 'EASY', pts: 100, time: 15, slug: 'crypto/easy-repeating-xor', topic: 'XOR cipher with known repeating key length' },
  { cat: 'CRYPTOGRAPHY', diff: 'EASY', pts: 100, time: 10, slug: 'crypto/easy-base58-layered', topic: 'Base58 and Base85 layered encoding with checksum' },
  { cat: 'CRYPTOGRAPHY', diff: 'MEDIUM', pts: 200, time: 30, slug: 'crypto/med-rsa-low-e', topic: 'RSA with low public exponent e=3 Coppersmith small root attack' },
  { cat: 'CRYPTOGRAPHY', diff: 'MEDIUM', pts: 250, time: 35, slug: 'crypto/med-aes-ecb-oracle', topic: 'AES-ECB mode block manipulation and oracle padding leak' },
  { cat: 'CRYPTOGRAPHY', diff: 'MEDIUM', pts: 250, time: 35, slug: 'crypto/med-dh-weak-prime', topic: 'Diffie-Hellman weak prime generator discrete log attack' },
  { cat: 'CRYPTOGRAPHY', diff: 'HARD', pts: 400, time: 60, slug: 'crypto/hard-aes-cbc-flip', topic: 'AES-CBC bit-flipping attack modifying encrypted token payloads' },
  { cat: 'CRYPTOGRAPHY', diff: 'HARD', pts: 450, time: 70, slug: 'crypto/hard-ecdsa-nonce', topic: 'ECDSA nonce reuse private key recovery' },
  { cat: 'CRYPTOGRAPHY', diff: 'HARD', pts: 450, time: 75, slug: 'crypto/hard-rsa-wiener', topic: 'RSA Wiener continued fractions attack on small private exponent d' },
  { cat: 'CRYPTOGRAPHY', diff: 'INSANE', pts: 750, time: 120, slug: 'crypto/insane-lll-knapsack', topic: 'Lattice-based cryptography LLL reduction on knapsack cryptosystem' },
  { cat: 'CRYPTOGRAPHY', diff: 'INSANE', pts: 850, time: 150, slug: 'crypto/insane-aes-fault', topic: 'Fault injection simulation on AES round key scheduling' },
  { cat: 'CRYPTOGRAPHY', diff: 'INSANE', pts: 900, time: 180, slug: 'crypto/insane-bleichenbacher', topic: 'Bleichenbacher RSA PKCS#1 v1.5 padding oracle adaptive attack' },

  // Category 5: FORENSICS
  { cat: 'FORENSICS', diff: 'EASY', pts: 100, time: 15, slug: 'forensics/easy-ext4-carve', topic: 'Hidden deleted file recovery from ext4 filesystem image' },
  { cat: 'FORENSICS', diff: 'EASY', pts: 100, time: 15, slug: 'forensics/easy-evtx-logon', topic: 'Windows Event Log (EVTX) logon artifact analysis' },
  { cat: 'FORENSICS', diff: 'EASY', pts: 100, time: 10, slug: 'forensics/easy-browser-sqlite', topic: 'Browser history and SQLite download database inspection' },
  { cat: 'FORENSICS', diff: 'MEDIUM', pts: 200, time: 30, slug: 'forensics/med-volatility-dll', topic: 'Volatility memory dump analysis extracting injected DLL' },
  { cat: 'FORENSICS', diff: 'MEDIUM', pts: 250, time: 35, slug: 'forensics/med-mft-timestomp', topic: 'Master File Table ($MFT) and NTFS $UsnJrnl timestamp anti-forensics investigation' },
  { cat: 'FORENSICS', diff: 'MEDIUM', pts: 250, time: 35, slug: 'forensics/med-pdf-javascript', topic: 'PDF format stream analysis with hidden JavaScript payload' },
  { cat: 'FORENSICS', diff: 'HARD', pts: 400, time: 60, slug: 'forensics/hard-linux-mem-keys', topic: 'Linux memory analysis with custom kernel profile to extract encryption keys' },
  { cat: 'FORENSICS', diff: 'HARD', pts: 450, time: 70, slug: 'forensics/hard-usb-shimcache', topic: 'USB device insertion forensics with Windows Registry shellbags and shimcache' },
  { cat: 'FORENSICS', diff: 'HARD', pts: 450, time: 75, slug: 'forensics/hard-tls-pcap-decrypt', topic: 'Network packet capture combined with SSL keylogfile decryption' },
  { cat: 'FORENSICS', diff: 'INSANE', pts: 750, time: 120, slug: 'forensics/insane-salsa20-mem', topic: 'Ransomware memory artifact extraction to recover ephemeral Salsa20 key' },
  { cat: 'FORENSICS', diff: 'INSANE', pts: 850, time: 150, slug: 'forensics/insane-firmware-spi', topic: 'Firmware SPI flash dump reverse engineering with compressed squashfs extraction' },
  { cat: 'FORENSICS', diff: 'INSANE', pts: 900, time: 180, slug: 'forensics/insane-hypervisor-rootkit', topic: 'Hypervisor memory snapshot introspection detecting rootkit hypercall hooks' },

  // Category 6: OSINT
  { cat: 'OSINT', diff: 'EASY', pts: 100, time: 15, slug: 'osint/easy-exif-geoloc', topic: 'Extracting EXIF geolocation metadata from reconnaissance photograph' },
  { cat: 'OSINT', diff: 'EASY', pts: 100, time: 15, slug: 'osint/easy-corp-email', topic: 'Corporate email pattern discovery and employee directory analysis' },
  { cat: 'OSINT', diff: 'EASY', pts: 100, time: 10, slug: 'osint/easy-git-history', topic: 'Public code repository commit history and leaked secret scanning' },
  { cat: 'OSINT', diff: 'MEDIUM', pts: 200, time: 30, slug: 'osint/med-whois-subdomain', topic: 'DNS subdomains enumeration and historical WHOIS archive correlation' },
  { cat: 'OSINT', diff: 'MEDIUM', pts: 250, time: 35, slug: 'osint/med-pgp-graph', topic: 'PGP public key server fingerprint and key signing graph investigation' },
  { cat: 'OSINT', diff: 'MEDIUM', pts: 250, time: 35, slug: 'osint/med-handle-recon', topic: 'Social media cross-platform handle correlation and timeline analysis' },
  { cat: 'OSINT', diff: 'HARD', pts: 400, time: 60, slug: 'osint/hard-ct-logs', topic: 'Certificate Transparency log analysis identifying staging infrastructure' },
  { cat: 'OSINT', diff: 'HARD', pts: 450, time: 70, slug: 'osint/hard-shadow-azimuth', topic: 'Satellite imagery analysis with sun shadow azimuth calculation for geolocation' },
  { cat: 'OSINT', diff: 'HARD', pts: 450, time: 75, slug: 'osint/hard-onion-tracking', topic: 'Leaked pastebin and darknet onion forum pseudonym tracking' },
  { cat: 'OSINT', diff: 'INSANE', pts: 750, time: 120, slug: 'osint/insane-crypto-cluster', topic: 'Blockchain cryptocurrency transaction graph clustering and mixing service de-anonymization' },
    { cat: 'OSINT', diff: 'INSANE', pts: 850, time: 150, slug: 'osint/insane-asn-sinkhole', topic: 'Autonomous System Number (ASN) BGP peering and DNS sinkhole infrastructure mapping' },
    { cat: 'OSINT', diff: 'INSANE', pts: 900, time: 180, slug: 'osint/insane-apt-infra', topic: 'Multi-source threat intelligence correlation of adversary APT C2 clusters' },

    // Category 7: REVERSE ENGINEERING
  { cat: 'REVERSE ENGINEERING', diff: 'EASY', pts: 100, time: 15, slug: 'rev/easy-string-transform', topic: 'Disassembling simple C binary with hardcoded string transformation' },
  { cat: 'REVERSE ENGINEERING', diff: 'EASY', pts: 100, time: 15, slug: 'rev/easy-pyc-decompile', topic: 'Python bytecode (.pyc) decompilation and control flow recovery' },
  { cat: 'REVERSE ENGINEERING', diff: 'EASY', pts: 100, time: 10, slug: 'rev/easy-js-obf-crackme', topic: 'Obfuscated JavaScript crackme key validation function' },
  { cat: 'REVERSE ENGINEERING', diff: 'MEDIUM', pts: 200, time: 30, slug: 'rev/med-xor-table', topic: 'x86-64 binary with custom byte substitution and XOR validation table' },
  { cat: 'REVERSE ENGINEERING', diff: 'MEDIUM', pts: 250, time: 35, slug: 'rev/med-golang-symbols', topic: 'Golang compiled binary symbol recovery and routine analysis' },
  { cat: 'REVERSE ENGINEERING', diff: 'MEDIUM', pts: 250, time: 35, slug: 'rev/med-apk-jni', topic: 'Android APK DEX reverse engineering and native JNI library analysis' },
  { cat: 'REVERSE ENGINEERING', diff: 'HARD', pts: 400, time: 60, slug: 'rev/hard-anti-debug-elf', topic: 'Anti-debugging techniques (ptrace, timing checks) in stripped ELF' },
  { cat: 'REVERSE ENGINEERING', diff: 'HARD', pts: 450, time: 70, slug: 'rev/hard-custom-vm', topic: 'Custom virtual machine interpreter bytecode disassembly' },
  { cat: 'REVERSE ENGINEERING', diff: 'HARD', pts: 450, time: 75, slug: 'rev/hard-cpp-vtable-obf', topic: 'C++ binary with virtual method table obfuscation and template metaprogramming' },
  { cat: 'REVERSE ENGINEERING', diff: 'INSANE', pts: 750, time: 120, slug: 'rev/insane-ollvm-flatten', topic: 'OLLVM control flow flattening with opaque predicates and instruction substitution' },
  { cat: 'REVERSE ENGINEERING', diff: 'INSANE', pts: 850, time: 150, slug: 'rev/insane-win-driver-ioctl', topic: 'Windows kernel driver (.sys) reverse engineering with IOCTL reversing' },
  { cat: 'REVERSE ENGINEERING', diff: 'INSANE', pts: 900, time: 180, slug: 'rev/insane-wasm-crypto-vm', topic: 'Obfuscated WebAssembly (Wasm) cryptographic key verification module' },

  // Category 8: BINARY EXPLOITATION
  { cat: 'BINARY EXPLOITATION', diff: 'EASY', pts: 100, time: 15, slug: 'pwn/easy-bof-win-func', topic: 'Classic 32-bit stack buffer overflow redirecting to win function' },
  { cat: 'BINARY EXPLOITATION', diff: 'EASY', pts: 100, time: 15, slug: 'pwn/easy-integer-overflow', topic: 'Integer overflow leading to out-of-bounds array access' },
  { cat: 'BINARY EXPLOITATION', diff: 'EASY', pts: 100, time: 10, slug: 'pwn/easy-fmt-str-leak', topic: 'Format string vulnerability leaking stack values' },
  { cat: 'BINARY EXPLOITATION', diff: 'MEDIUM', pts: 200, time: 30, slug: 'pwn/med-ret2libc-nx', topic: 'Ret2libc exploit bypassing NX with system and /bin/sh arguments' },
  { cat: 'BINARY EXPLOITATION', diff: 'MEDIUM', pts: 250, time: 35, slug: 'pwn/med-fmt-str-got-write', topic: 'Format string vulnerability overwriting GOT entry with target address' },
  { cat: 'BINARY EXPLOITATION', diff: 'MEDIUM', pts: 250, time: 35, slug: 'pwn/med-x64-rop-execve', topic: 'ROP chain on x86-64 binary to execute execve syscall' },
  { cat: 'BINARY EXPLOITATION', diff: 'HARD', pts: 400, time: 60, slug: 'pwn/hard-tcache-poison', topic: 'Heap exploitation: fastbin dup and tcache poisoning leading to arbitrary write' },
  { cat: 'BINARY EXPLOITATION', diff: 'HARD', pts: 450, time: 70, slug: 'pwn/hard-srop-syscall', topic: 'SROP (Sigreturn Oriented Programming) binary exploitation' },
  { cat: 'BINARY EXPLOITATION', diff: 'HARD', pts: 450, time: 75, slug: 'pwn/hard-ret2csu-pie', topic: 'Ret2csu exploitation technique on PIE-disabled binaries' },
  { cat: 'BINARY EXPLOITATION', diff: 'INSANE', pts: 750, time: 120, slug: 'pwn/insane-fsop-stdout', topic: 'Modern glibc 2.35+ heap exploitation (house of apple / FSOP stdout vtable hijacking)' },
  { cat: 'BINARY EXPLOITATION', diff: 'INSANE', pts: 850, time: 150, slug: 'pwn/insane-brop-remote', topic: 'Blind ROP (BROP) over network service without binary source' },
  { cat: 'BINARY EXPLOITATION', diff: 'INSANE', pts: 900, time: 180, slug: 'pwn/insane-kernel-slab-oob', topic: 'Linux kernel exploitation: slab out-of-bounds write to modify cred structure' },

  // Category 9: PRIVILEGE ESCALATION
  { cat: 'PRIVILEGE ESCALATION', diff: 'EASY', pts: 100, time: 15, slug: 'privesc/easy-suid-path', topic: 'SUID binary with relative PATH environment variable hijacking' },
  { cat: 'PRIVILEGE ESCALATION', diff: 'EASY', pts: 100, time: 15, slug: 'privesc/easy-passwd-writable', topic: 'World-writable /etc/passwd file enabling new root user creation' },
  { cat: 'PRIVILEGE ESCALATION', diff: 'EASY', pts: 100, time: 10, slug: 'privesc/easy-cron-tmp-script', topic: 'Insecure cron job script executing writable files in /tmp' },
  { cat: 'PRIVILEGE ESCALATION', diff: 'MEDIUM', pts: 200, time: 30, slug: 'privesc/med-systemd-unit', topic: 'Insecure systemd service unit file with writable ExecStart' },
  { cat: 'PRIVILEGE ESCALATION', diff: 'MEDIUM', pts: 250, time: 35, slug: 'privesc/med-sudo-preload', topic: 'Sudo LD_PRELOAD / env_keep configuration vulnerability' },
  { cat: 'PRIVILEGE ESCALATION', diff: 'MEDIUM', pts: 250, time: 35, slug: 'privesc/med-docker-socket', topic: 'Docker socket group membership root container escape' },
  { cat: 'PRIVILEGE ESCALATION', diff: 'HARD', pts: 400, time: 60, slug: 'privesc/hard-dirtypipe-cache', topic: 'Dirty Pipe (CVE-2022-0847) page cache overwrite exploit analysis' },
  { cat: 'PRIVILEGE ESCALATION', diff: 'HARD', pts: 450, time: 70, slug: 'privesc/hard-seimpersonate', topic: 'Windows Token Impersonation (SeImpersonatePrivilege / RottenPotato style)' },
  { cat: 'PRIVILEGE ESCALATION', diff: 'HARD', pts: 450, time: 75, slug: 'privesc/hard-pwnkit-pkexec', topic: 'Polkit (PwnKit CVE-2021-4034) pkexec local privilege escalation' },
  { cat: 'PRIVILEGE ESCALATION', diff: 'INSANE', pts: 750, time: 120, slug: 'privesc/insane-ebpf-verifier', topic: 'Linux eBPF verifier flaw privilege escalation' },
  { cat: 'PRIVILEGE ESCALATION', diff: 'INSANE', pts: 850, time: 150, slug: 'privesc/insane-win-pool-corrupt', topic: 'Windows kernel pool corruption via vulnerable third-party driver' },
  { cat: 'PRIVILEGE ESCALATION', diff: 'INSANE', pts: 900, time: 180, slug: 'privesc/insane-rowhammer-bitflip', topic: 'Hardware rowhammer simulation memory bitflip privilege escalation' },

  // Category 10: ACTIVE DIRECTORY
  { cat: 'ACTIVE DIRECTORY', diff: 'EASY', pts: 100, time: 15, slug: 'ad/easy-ldap-anon-enum', topic: 'Anonymous LDAP binding enumeration and user account extraction' },
  { cat: 'ACTIVE DIRECTORY', diff: 'EASY', pts: 100, time: 15, slug: 'ad/easy-pass-spray-log', topic: 'Password spray log analysis identifying compromised user credentials' },
  { cat: 'ACTIVE DIRECTORY', diff: 'EASY', pts: 100, time: 10, slug: 'ad/easy-gpp-cpassword', topic: 'Group Policy Preference (GPP) cpassword decryption from SYSVOL share' },
  { cat: 'ACTIVE DIRECTORY', diff: 'MEDIUM', pts: 200, time: 30, slug: 'ad/med-kerberoast-spn', topic: 'Kerberoasting attack on Service Principal Names (SPN) with hash cracking' },
  { cat: 'ACTIVE DIRECTORY', diff: 'MEDIUM', pts: 250, time: 35, slug: 'ad/med-asrep-roast', topic: 'AS-REP Roasting on accounts with Do Not Require Kerberos Preauthentication' },
  { cat: 'ACTIVE DIRECTORY', diff: 'MEDIUM', pts: 250, time: 35, slug: 'ad/med-dns-acl-hijack', topic: 'Insecure DNS update ACL enabling Active Directory DNS record hijacking' },
  { cat: 'ACTIVE DIRECTORY', diff: 'HARD', pts: 400, time: 60, slug: 'ad/hard-adcs-esc1', topic: 'Active Directory Certificate Services (ADCS) ESC1 template exploitation' },
  { cat: 'ACTIVE DIRECTORY', diff: 'HARD', pts: 450, time: 70, slug: 'ad/hard-bloodhound-delegation', topic: 'BloodHound graph analysis identifying unconstrained Kerberos delegation path' },
  { cat: 'ACTIVE DIRECTORY', diff: 'HARD', pts: 450, time: 75, slug: 'ad/hard-dcsync-repl', topic: 'DCSync attack via replication rights (DS-Replication-Get-Changes)' },
  { cat: 'ACTIVE DIRECTORY', diff: 'INSANE', pts: 750, time: 120, slug: 'ad/insane-golden-ticket-pac', topic: 'Golden Ticket and Silver Ticket forgery with RC4/AES256 keys and PAC manipulation' },
      { cat: 'ACTIVE DIRECTORY', diff: 'INSANE', pts: 850, time: 150, slug: 'ad/insane-forest-trust-sid', topic: 'Cross-forest SID filtering bypass and forest trust hop privilege escalation' },
      { cat: 'ACTIVE DIRECTORY', diff: 'INSANE', pts: 900, time: 180, slug: 'ad/insane-rbcd-machine-quota', topic: 'Resource-Based Constrained Delegation (RBCD) combined with machine account quota' }
    ]
  };
